### ISSUE TITLE
[Bug] [1656] Novels in Listing View Duplicating

### ISSUE THREAD

**Issue by Dunbock** [shosetsuorg/shosetsu#150]
**Describe the bug**
Selecting a novel of the listing and going back to the listing duplicates all novels.
Further, additional novels only load after selecting a novel and backing out.

**To Reproduce**
1. Select an extension (tested with AsianHobbyist (non-incrementing listing) and ReadLightNovel (incrementing listing)).
2. Select any novel.
3. Hit the back button.
4. See the novels duplicated in the listing view.
5. See more novels appearing when scrolling down in a incremental listing view.

**Expected behavior**
Going back from a novel should not duplicate the novels in the listing view.
Further, in a incremental listing view additional novels should load without having to select a novel first.

**Device information:**
 - OS: Android 11
 - App Version: 1656

**Comment by Doomsdayrs** [comment]
It has finally come, someone has made an issue in regards to the broken listing mechanics of Shosetsu.

The solution to this issue is using the android paging library instead and simplifying the catalogue codebase.

**Comment by Doomsdayrs** [comment]
Android paging has been implemented. @Dunbock does this still occur?

**Comment by Dunbock** [comment]
I have not updated due to not using Shosetsu at the moment. Looking back, this issue boils down to the starting page being page 0 and as a result of page 0 equals page 1 on most sites the first page gets duped. So if the change to start with page 1 instead of 0 by default works then this problem should be solved.
