### ISSUE TITLE
[Bug] [2.0.0-1656] Top of screen eats top of filter menu

### ISSUE THREAD

**Issue by khonkhortisan** [shosetsuorg/shosetsu#155]
**Describe the bug**
When a filter group is expanded so that the top of the filter list can go off the top of the screen, the top of the filter list is cropped when it's off the top of the screen and then scrolled back into view. This happens whether it was pushed off the screen by expanding or by scrolling

**To Reproduce**
1. Hold phone in landscape mode so you can do this with a shorter menu
2. Expand all Filtergroups
3. Scroll to push the top of the filter menu off the top of the screen
4. Scroll to pull the top of the filter menu back down
5. See that the top of the menu is missing

**Expected behavior**
The filter menu would scroll or expand past the top of the screen, then scroll or collapse safely back without cropping the top of the menu.

**Screenshots**
![Screenshot_20211114-005653_Shosetsu](https://user-images.githubusercontent.com/1996449/141676199-aac21f55-9245-4fc2-be0b-bebe76841a75.jpg)
<img src="https://user-images.githubusercontent.com/1996449/141668146-7ab137c1-98c3-47c5-b04e-ac9977c617f4.jpg" width="20%"> <img src="https://user-images.githubusercontent.com/1996449/141668143-69c4a9b3-6a86-405f-8ceb-e64b292d4a51.jpg" width="20%"> <img src="https://user-images.githubusercontent.com/1996449/141668136-909cc196-8495-4e8c-92db-8354f8c1397d.jpg" width="20%"> <img src="https://user-images.githubusercontent.com/1996449/141668117-6e688e75-d91f-46e8-8a31-de4435b0daeb.jpg" width="20%">
<img src="https://user-images.githubusercontent.com/1996449/141669497-fd3a1202-4e67-4def-ba3f-fa7923bf2756.jpg" width="20%"> It can crop in the middle of an element, not just between them

**Device information:**
 - OS: Android 10, One UI 2.0
 - App Version: 2.0.0-1656
 - Phone: Samsung Galaxy A20 SM-A205U
 - Display: 2340×1080 virtual resolution downscaled onto a 1560×720 physical display (1.5² pixels in every 1² pixel)

AND
- BlueStacks 5.3.145.1003 N64, 1 core, 900MB memory, low memory performance mode, 30fps, portrait 540×960, 240 dpi, phone: OnePlus 5, ATNT

**Additional context**

**Comment by khonkhortisan** [comment]
There are two layers of scrolling going on here: ¹the list of checkboxes in the filter menu, ²the filter pop-up itself
1. expand all of NOVA's filter groups, lowest to highest
2. push the top of the filter pop-up to the top of the screen and no further²
3. touch the screen, push up to scroll checkboxes up¹, push down to scroll back¹. No options disappear!
4. touch the screen, push up to scroll checkboxes up¹, let go, touch the screen again, push down². The filter pop-up is pulled down from the screen, while some of the checkboxes are still scrolled past the top of the pop-up.

What should happen is
4. touch the screen, push up to scroll checkboxes up¹, let go, touch the screen again, push down¹, the checkboxes are brought back,
   a. they stop scrolling¹ and you have to re-tap the screen to start scrolling the filter pop-up² OR
   b. it seamlessly switches from scrolling the checkboxes¹ to scrolling the filter pop-up²
   b is better than a

**Comment by khonkhortisan** [comment]
reference: https://material.io/components/sheets-bottom
I tested this in bluestacks at 540×960 resolution, and noticed that the library FILTER works correctly. When all the filters are expanded:
A. half popup:
    ⇑ pushing the titlebar up moves the popup to the top of the screen
    ⇓ pushing the titlebar down closes the popup
-  checkboxes visible:
    ⇑ pushing the checkboxes up moves the popup to the top of the screen
    ⇓ pushing the checkboxes down closes the popup
-  checkboxes too high:
    ⇑ pushing the checkboxes up moves the popup to the top of the screen
    ↑↓ pushing the checkboxes up then down scrolls the checkboxes down
    ↓ pushing the checkboxes down scrolls the checkboxes down

B. fullscreen popup:
  ⇑ pushing the titlebar up does nothing
  ⇓ pushing the titlebar moves it to the middle of the screen
- checkboxes visible:
    ↑ pushing the checkboxes up scrolls the checkboxes up
    ⇓ pushing the checkboxes down scrolls
- checkboxes too high:
    ↑ pushing the checkboxes up does nothing
    ⇓ pushing the checkboxes down moves the popup to the middle of the screen

This ended up complicated enough that I made a flowchart for both the library and extension popup behavior in graphviz
![shosetsu-155-top-of-screen](https://user-images.githubusercontent.com/1996449/143881548-34b9d93c-8e6e-4b6a-b66c-ebbe83c52115.png)
[shosetsu-155-top-of-screen.gv.txt](https://github.com/shosetsuorg/android-app/files/7618629/shosetsu-155-top-of-screen.gv.txt)
When the popup is half-open with the checkboxes scrolled too high:
- in the library you can tap outside the popup to close it, pull the titlebar up to fullscreen it, pull the titlebar down to close it, or pull the center down to fix the position of the checkboxes and then pull the center down to close the popup.
- in an extension you can tap outside the popup to close it, pull it up to fullscreen it, or pull it down to close it.

When everything is as high as it'll go:
- in the library you can take either path back to a closed popup, by deciding whether you'll pull the titlebar or the center.
- in an extension to take the visible checkboxes path you must first attempt to scroll the checkboxes up even further before it'll let you scroll them down, otherwise you take the hidden checkboxes path back to a closed popup.

**Comment by Doomsdayrs** [comment]
The filter menu is composed currently of two different view types. 

The actual "Popup" is an android BottomSheetDialog, while the contents are composed of Compose views.

Because of this, I believe the BottomSheetDialog scroll mechanics are coming into play and interfering with how Compose is handling view scrolling.

As it currently stands, I do not know how to properly handle this.
