### ISSUE TITLE
[Bug] Back gesture doesn't work properly in reader. [r2050]

### ISSUE THREAD

**Issue by THElegend5** [shosetsuorg/shosetsu#190]
**Describe the bug**
The back gesture doesn't work in the upper half of the screen in the reader, works normally everywhere else in the app.

**To Reproduce**
1. Open any chapter of any novel.
2. Try to use back gesture on the upper half of the screen.
3. You aren't able to exit out of reader.

**Expected behavior**
You exit out of the reader.

**Device information:**
 - OS: 11
 - App Version: 2.0.0-2050

**Additional context**
The back gesture works fine on the lower half of the screen.

**Comment by Doomsdayrs** [comment]
Please do note that bugs with super secret test releases are meant to be pinged to me directly.

Regardless, This is unconfirmed.

Please note that some ROMs limit the back gesture to certain parts of the screen.

**Comment by THElegend5** [comment]
> Please do note that bugs with super secret test releases are meant to be pinged to me directly.
> 
> Regardless, This is unconfirmed.
> 
> Please note that some ROMs limit the back gesture to certain parts of the screen.

Ah my bad it is rom related , honestly i never use that part of the screen to go back so makes sense , this one just came up while talking on matrix so thought it was related to #187. And it had been there since as far back as i can remember.
