### ISSUE TITLE
[Bug] [VERSION] "End of input at character 0 of" bug

### ISSUE THREAD

**Issue by UnknownAzzwipe** [shosetsuorg/shosetsu#204]
**Descwibe the bwug**
Error while reading or downloading

**To Wepwoduce**
Steps to wepwoduce the behaviow:
No clue how to reproduce

**Expected behaviow**
To read or download without this error

**Scweenshots**

**Device infowmation:**
 - OS: Android 11
 - App Version: 2.0.0-2089

**Additional context**

**Comment by Doomsdayrs** [comment]
This seems to be an extension issue, What extension is it?

**Comment by Doomsdayrs** [comment]
https://github.com/shosetsuorg/extensions/issues
