### ISSUE TITLE
[F-R]Give overlay to this upper bar

### ISSUE THREAD

**Issue by Palloxin** [shosetsuorg/shosetsu#206]
![IMG_20220516_074417](https://user-images.githubusercontent.com/75091899/168526911-67f018b3-9c08-46bb-af65-e6708670e02b.jpg)
this upper bar should overlay on the reader not distort the shape of the text container like in the video:

https://user-images.githubusercontent.com/75091899/168527195-353c7faa-91c4-45cb-bfa5-3229eb5d15c1.mp4

the lower bar has already the overlay, the upper one does not.

**Comment by Doomsdayrs** [comment]
Upper bar has been removed completely.

**Comment by Palloxin** [comment]
you mean in the next version?
