### ISSUE TITLE
[Bug] [2186] Heavy lag occours and accumulate over time after normal use

### ISSUE THREAD

**Issue by Palloxin** [shosetsuorg/shosetsu#208]
**Describe the bug**
Heavy lag occours and increse over time with normal use of the app.

**To Reproduce**
1. start reading until tge scrolling of the reader starts to lag, it happens every time and it just needs time using the app without closing it.

**Expected behavior**
no lag while using the app

**Screenshots**

https://user-images.githubusercontent.com/75091899/169690513-7ec2a1e6-31f3-4c6a-b488-a36a56a309db.mp4

**Device information:**
 - OS: Android 8
 - App Version: 2.0 r2186

over time the lag gets heavier and heavier. to resolve it i close the app and it returns to normal

**Comment by Doomsdayrs** [comment]
Are you using custom CSS?

What novel is that?

How many chapters did you read before that started happening ?

**Comment by Palloxin** [comment]
> Are you using custom CSS?
> 
> What novel is that?
> 
> How many chapters did you read before that started happening ?

Yes
Overgeared on BestLightNovel
i don't know, i didn't count.

**Comment by Doomsdayrs** [comment]
Can you paste the CSS here?

**Comment by Palloxin** [comment]
> Can you paste the CSS here?

@import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@300&display=swap');

body {font-family: 'Merriweather';padding: 1px;color: #f0f0f0}

hr {border: 2px solid; border-radius: 300px;} 

p { text-indent: 3px !important;line-height:1.8}

**Comment by Doomsdayrs** [comment]
This issue seems to lead to certain devices crashing under the strain due to OOM.

**Comment by Doomsdayrs** [comment]
Solved OOM issues, next release will have it fixed
