### ISSUE TITLE
[F-R]Add a way to cancel titles of chapters because they are spoilers

### ISSUE THREAD

**Issue by Palloxin** [shosetsuorg/shosetsu#215]
**Is your feature request related to a problem? Please describe.**
titles of chapters are just spoilers and who want to be spoilered? i want just the number of the chapter.

**Describe the solution you'd like**
delete the titles of chapters

**Describe alternatives you've considered**

**Additional context**

**Comment by Doomsdayrs** [comment]
The author INTENDS for you to see such. It would ruin the reading experience and format authors expect.

I will not implement this.

**Comment by Palloxin** [comment]
> The author INTENDS for you to see such. It would ruin the reading experience and format authors expect.
> 
> I will not implement this.

@Doomsdayrs alright, i will rephrase it. let users choose if they want to see title because some see them as spoiler, doesn't matter the wish of the author if they don't want to see them.
