### ISSUE TITLE
[F-R]

### ISSUE THREAD

**Issue by xeusninja** [shosetsuorg/shosetsu#217]
Would be nice to have an Epub converter function in the app.
I don't have a good knowledge on programming and development, so i don't know if it will be possible. But, would be nice to see it in the app. 

Saw that feature in another well developed app called "quick novel".

Here's their github: https://github.com/LagradOst/QuickNovel

P.S:- Thank you very much Developer for making this app. I have been using it for a while and the experience has been really great.
Keep up the good work.
Thanks again for giving us this amazing app.

**Comment by Doomsdayrs** [comment]
Sorry, EPUB is a complex standard, and I will not work on it. If someone else knows how to implement this, I will be open for commits.

**Comment by xeusninja** [comment]
Oh. Okay. Thanks for the reply and thanks for letting me know.

Keep up the good work.

Sincerely,
Mohammad Kashif
