### ISSUE TITLE
[F-R] Chapter range download

### ISSUE THREAD

**Issue by RunicAce** [shosetsuorg/shosetsu#234]
**Is your feature request related to a problem? Please describe.**
Yes, downloads will be limited to 999 chapters (based on my understanding of the new update).

**Describe the solution you'd like**
In the 'download' menu, add "range download." This way, we can download chapters 1 thru 999, then after that is finished, we can download chapter 1000 thru 1998, and so on until all chapters are downloaded.

**Describe alternatives you've considered**
Hit download unread. If limited to 999, then write down your current chapter number(ex: chapter 41) then mark all your downloaded chapters as read, and repeat the process until all chapters are downloaded. Then mark  whatever you didn't read, as unread(ex: selecting chapter 41 thru 2176, and marking them as unread)

**Additional context**
If the downloads are limited to 999 maximum downloads, then having this feature would improve convenience of the app.

**Comment by Doomsdayrs** [comment]
No, That is not what the update does.

It chunks the large updates to 999 updates per query.
