### ISSUE TITLE
[Bug] [App lags] 

### ISSUE THREAD

**Issue by Axillman** [shosetsuorg/shosetsu#240]
**Describe the bug**
The app freezes and becomes unresponsive making me unable to scroll

**To Reproduce**
1. It becomes unresponsive 
2. It freezes 
3.  Crashes 

**Expected behavior**
The app should not lag.

**Screenshots**
https://user-images.githubusercontent.com/109915412/184531627-ea3cf0ab-8186-4690-943e-e86ef26d040c.mp4

**Device information:**
 - OS: Android OS
 - App Version: 2.0.0-2411

**Additional context**
@Doomsdayrs plz help

**Comment by Doomsdayrs** [comment]
Please provide more information.

**Comment by Axillman** [comment]
[Help wanted]

**Comment by HikaruIchijyo** [comment]
> Please provide more information.

Some minor glitches & lags especially that download thread one & extensions page

> https://arvanloud.io/dl_15177019/Screenrecorder-2022-08-15-13-15-34-413.mp4
