### ISSUE TITLE
[F-R] Browse Filtering

### ISSUE THREAD

**Issue by CrepeTF** [shosetsuorg/shosetsu#98]
**Is your feature request related to a problem?**
Difficult to find curated novels intuitively

**Describe the solution you'd like**
Add filter by genre feature (should the website support it)

**Describe alternatives you've considered**
N/a

**Additional context**
Unlocks UI Mock-ups

**Comment by Doomsdayrs** [comment]
I added the bare bones of the filter menu, and it should work in all case. 

Just need to write up a script to ensure that it works reliably

**Comment by Doomsdayrs** [comment]
This has all been implemented
